on:
  workflow_call:
    inputs:
      PROJECT_NUMBER:
        required: true
        type: number
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo Project ${{ inputs.PROJECT_NUMBER }}
