on: [workflow_call]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          github-token: ${{ secrets.MODERATOR_PAT }}
          script: |
            const {PROJECT_ID} = process.env;
            const query = `query($projectId:ID!) {
              node(id:$projectId) {
                ... on ProjectV2 {
                  items(first: 20) {
                    nodes {
                      id
                      content
                    }
                  }
                }
              }
            }`;
            const variables = {
              projectId: PROJECT_ID,
            };
            const result = await github.graphql(query, variables);
            console.log(JSON.stringify(result, null, 2));
