on: [workflow_call]
jobs:
  assign:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - if: |
          (
            toJSON(github.event.pull_request.assignees) == '[]'
            || toJSON(github.event.issue.assignees) == '[]'
          )
          && github.actor != 'dependabot[bot]'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.actor]
            });
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.MODERATOR_PAT }}
