on: [workflow_call]
jobs:
  assign:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - if: |
          toJSON(github.event.issue.assignees) == '[]'
          && github.actor != 'dependabot[bot]'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.actor]
            });
      - if: github.event.pull_request
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr) {
              const matched = (/^(\d+)-/).exec(pr.head.ref);
              if (matched) {
                const issueNumber = matched[1];
                const prefix = `GH-${issueNumber}: `;
                if (!pr.title.startsWith(prefix)) {
                  const params = {
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: pr.title.replace(/^(\s+gh\s*-\d+\s*:)?\s*/i, prefix),
                  };
                  console.info(params);
                  await github.rest.issues.update(params);
                }
                const linkPattern = new RegExp(`(close[sd]?|fix(e[sd])?|resolve[sd]?)\\s+#${issueNumber}`, 'i');
                if (!linkPattern.test(pr.body)) {
                  const docUrl = 'https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue';
                  const params = {
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `The PR body has no [links](docUrl) to #${issueNumber}.`,
                  };
                  console.info(params);
                  await github.rest.issues.createComment(params);
                }
              }
            }
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.MODERATOR_PAT }}
